### ISSUE TITLE
Bug: Rust wrapper fails to load index correctly from buffer or file.

### ISSUE THREAD

**Issue by voxelbee** [unum-cloud/usearch#458] opened 2024-08-09 11:55 UTC
### Describe the bug

In the Rust wrapper when reloading the index from a serialized version making any calls to search on the deserialized index causes an exception: "No available threads to lock". This happens with both `load()` and `load_from_buffer()`. 

I have ran the C and C++ tests and the load and save tests pass fine on my machine.

failures:

---- tests::integration stdout ----
--------------------------------------------------
before add, memory_usage: 1792 cap: 64 
after add, memory_usage: 20973248 cap: 64 
Matches { keys: [43, 42], distances: [1.0, 1.0] }
Matches { keys: [43, 42], distances: [1.0, 1.0] }
--------------------------------------------------
thread 'tests::integration' panicked at rust/lib.rs:1572:46:
search failed: Exception { what: "No available threads to lock" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    tests::integration

test result: FAILED. 8 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

### Steps to reproduce

Change the rust tests in `rust/lib.rs` at line 1572 to try and make a search on the `deserialized_index`.

```rust
let mut serialization_buffer = Vec::new();
serialization_buffer.resize(index.serialized_length(), 0);
assert!(index.save_to_buffer(&mut serialization_buffer).is_ok());

let deserialized_index = new_index(&options).unwrap();
assert!(deserialized_index
    .load_from_buffer(&serialization_buffer)
    .is_ok());
assert_eq!(index.size(), deserialized_index.size());

// **ERROR:** The new code to check the search works on the loaded index
deserialized_index.search(&first, 5).expect("search failed");
```

### Expected behavior

We expect that the deserialized_index should not fail when calling search.

### USearch version

v2.13.1

### Operating System

MacOS Sonoma 14.5

### Hardware architecture

Arm

### Which interface are you using?

Other bindings

### Are you open to being tagged as a contributor?

- [X] I am open to being mentioned in the project `.git` history as a contributor

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by estokes** [comment] 2024-08-10 15:02
I also encountered this issue, also using the rust binding, with indexes saved to disk, loaded again, updated, and saved to the same file.

**Comment by ashvardanian** [comment] 2024-08-10 18:31
Good to know, will look into it today.

**Comment by estokes** [comment] 2024-08-10 20:04
A little more detail, I'm loading the index with view. I confirmed that at the end of the view method in index_dense.hpp, self.available_threads_.size() is 0. I currently create the index and then immediately call view, however if I change this to create the index, reserve(10), and then call view it works. I don't see that self.available_threads_ is being initialized in the constructor, so my guess is it isn't being initialized ever unless reserve is called.

**Comment by ashvardanian** [comment] 2024-08-12 03:22
Thank you @estokes and @voxelbee! The issue seems to be fixed now, pushing soon 🤗

**Closed** 2024-08-12 05:48 UTC
Labels: bug
